### ISSUE TITLE
Lean option

### ISSUE THREAD

**Issue by AlbertoJALJ** [LucaIaconelli/mongoose-paginate-ts#6]
Hi, is there any way to use lean method in the query?

**Comment by LucaIaconelli** [comment]
Hey @AlbertoJALJ,

The lean option is already done by default if the query is not an aggregate (as you can see inside the code). 

For now, there is no option to disable it, but I can add this option asap. 

Thanks

**Comment by AlbertoJALJ** [comment]
Thanks!
